spring.application.name=flexisaf

spring.config.import=optional:classpath:application.yml

# JWT Configuration
app.jwt.secret=VGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgSldUIHNpZ25pbmcuIFBsZWFzZSByZXBsYWNlIHdpdGggeW91ciBvd24gc2VjdXJlIGtleSBpbiBwcm9kdWN0aW9uLg==
app.jwt.expiration=86400000

# Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true